[pytest]
addopts = --cov=game_helper --cov=game_window --cov-report=term-missing --cov-report=xml --cov-fail-under=5
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
